vim.keymap.set('n', '<leader>e', '<cmd>Ex<cr>')
vim.keymap.set('n', '<leader><cr>', '<cmd>so<cr>')
vim.keymap.set('n', '<C-s>', '<cmd>:w<cr>')
vim.keymap.set('i', '<C-S>', '<Esc><cmd>:w<cr>')
vim.keymap.set('n', '<C-x>', '<cmd>:bdelete<cr>')
