[packages]
names = [
	"neovim",
	"git",
	"alacritty",
	"fzf",
	"zsh",
	"clang",
	"make",
	"cmake",
	"tldr",
	"thefuck",
	#"lazygit",
	#"lazydocker",
	"httpie"
]

[cargo_install]
names = [
	"zoxide",
	"fd-find",
	"duf",
	"ripgrep",
	"bat",
	"exa",
	"starship",
	"rm-improved",
	"sd",
	"procs",
	"bandwhich",
	"macchina"
]
