[packages]
names = [
	"neovim",
	"git",
	"alacritty",
	"fzf",
	"zsh",
	"clang",
	"make",
	"cmake",
	"tldr",
	"thefuck",
	"httpie",
	"libXft-devel",
	"libX11-devel",
	"libXinerama-devel",
	"duf",
  "bat",
  "ripgrep",
  "gh"
]

[cargo_install]
names = [
	"zoxide",
	"fd-find",
	"exa",
	"starship",
	"rm-improved",
	"sd",
	"procs",
	"bandwhich",
]

[git]
name='williamzborja'
email='williamzborja@mail.com'
