[packages]
names = [
	"neovim",
	"git",
	"alacritty",
	"fzf",
	"zsh",
	"clang",
	"make",
	"cmake",
	"tldr",
	"thefuck",
	"httpie",
	"duf",
  "bat",
  "ripgrep",
  "gh",
  "tmux",
  "fd-find",
#  --- RWM
  "xorg-x11-server-Xwayland",
  "xorg-x11-server-common",
	"libXft-devel",
	"libX11-devel",
	"libXinerama-devel",
  "xorg-x11-xinit",
  "libXi",
  "picom",
  "feh",
  "clang-tools-extra", #clangd
  "rofi"
]

[cargo_install]
names = [
	"exa",
	"rm-improved",
	"sd",
	"procs",
	"bandwhich",
]

[git]
name='williamzborja'
email='williamzborja@mail.com'

[[shell_package]]
name="zoxide"
url="https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh"

[[shell_package]]
name="ohmyzsh"
url="https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

[[shell_package]]
name="starship"
url="https://starship.rs/install.sh"
